DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS role;

CREATE TABLE IF NOT EXISTS role (
id BIGINT UNSIGNED      NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30)        NOT NULL
);

CREATE TABLE IF NOT EXISTS user (
id BIGINT UNSIGNED      NOT NULL AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(70)    NOT NULL,
password VARCHAR(72)    NOT NULL,
role_id BIGINT UNSIGNED NOT NULL, FOREIGN KEY (role_id) REFERENCES role(id)
);

CREATE TABLE IF NOT EXISTS item (
id BIGINT UNSIGNED  NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(80)    NOT NULL,
status VARCHAR(6)   NOT NULL
);

INSERT INTO role (name) VALUES ('ADMINISTRATOR');
INSERT INTO role (name) VALUES ('CUSTOMER');

INSERT INTO user (username,password,role_id) VALUES (
'admin',
'$2a$12$L9eDNHoC6pGJuQAdg4aL6OB1DlCwMObWUPqcpSFoxnah9nxTZbr7m',
(SELECT id FROM role WHERE name='ADMINISTRATOR')
);
INSERT INTO user (username,password,role_id) VALUES (
'user',
'$2a$10$l6wRkqfxG9xtKLDBunBtt.xgQ8VTmSKXa4HzRImvB03tGo/xzmuwG',
(SELECT id FROM role WHERE name='CUSTOMER')
);

INSERT INTO item (name,status) VALUES ('item1','READY');
INSERT INTO item (name,status) VALUES ('item2','STEADY');
INSERT INTO item (name,status) VALUES ('item3','GO');
